AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  job-scraper

  Sample SAM Template for job_scraper

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Environment:
      Variables:
        JOBS_TABLE: !Select [1, !Split ['/', !GetAtt Jobs.Arn]]

Resources:
  JobScraperFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda/
      Handler: src.app.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64
      Events:
        CloudWatchSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 day)'
            Name: job_scraper
            Description: Cloud Watch Trigger used to run this function once a day
            Enabled: true
      Policies:
      - DynamoDBCrudPolicy: 
          TableName: !Select [1, !Split ['/', !GetAtt Jobs.Arn]]
  Jobs:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: type
          AttributeType: S
        - AttributeName: jobUrl
          AttributeType: S
      KeySchema: 
        - AttributeName: type
          KeyType: HASH
        - AttributeName: jobUrl
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  Users:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: user_id
          AttributeType: S
      KeySchema: 
        - AttributeName: user_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
